### ISSUE TITLE
Bring front-end code to this repo

### ISSUE THREAD

**Issue by ardeshirj** [RadVenturepdx/Capn-Crunch#12]
Bring the header and footer to this repo. Also bring the sing in/up inside this repo as well.

**Comment by ardeshirj** [comment]
Will work with @sector46 to move this forward.

Ardeshir is going to create the branch.

**Comment by CATcommander** [comment]
I can also help out you guys if you need it.

**Comment by ardeshirj** [comment]
Front-end people suggest to bring these pages
Index.html (Take out header and footer to separate file)
contact
about.html
faq.html

**Comment by melyan** [comment]
Please also bring in these 2 pages, they're done:
registration-user.html
registration-guide.html

**Comment by ardeshirj** [comment]
What needs to be fixed:

- Padding for navigation bar
- Loading the pictures from a file server
