### ISSUE TITLE
Update navbar to new html from front-end

### ISSUE THREAD

**Issue by ardeshirj** [RadVenturepdx/Capn-Crunch#14]
Initially the user should see log in and sign up, but once they log in they should only see a drop down that has "Account Settings" and "Log out"

**Comment by CATcommander** [comment]
I updated the navbar from front-end. Let me know if anything needs to be changed.

**Comment by CATcommander** [comment]
Log in part is done. The user can now see Account settings and log out option. Working on Sign up.
