### ISSUE TITLE
Ticket #15 Pull Request fails two unit tests.

### ISSUE THREAD

**Issue by beazley2** [RadVenturepdx/Capn-Crunch#19]
1) Error:
StaticPagesControllerTest#test_should_get_home:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/views/static_pages/home.html.erb:9:in `block in _app_views_static_pages_home_html_erb___841558002_97090704'
    app/views/static_pages/home.html.erb:4:in `_app_views_static_pages_home_html_erb___841558002_97090704'
    test/controllers/static_pages_controller_test.rb:5:in `block in <class:StaticPagesControllerTest>'

  2) Error:
UsersLoginTest#test_login_with_valid_information_followed_by_logout:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/views/static_pages/home.html.erb:9:in `block in _app_views_static_pages_home_html_erb___841558002_97090704'
    app/views/static_pages/home.html.erb:4:in `_app_views_static_pages_home_html_erb___841558002_97090704'
    test/integration/users_login_test.rb:17:in `block in <class:UsersLoginTest>'

45 runs, 59 assertions, 0 failures, 2 errors, 0 skips

**Comment by lewisric** [comment]
Looks like this is a common error that has many potential issues. could just be a config file update, or it could be undefined class references.  Ill try to get more information for it later today.

**Comment by CATcommander** [comment]
@beazley2 can you try changing *<h3><%= guides.user.name %></h3>* in *(app/views/static_pages/home.html.erb line 9)* to either one of these and see if it resolves the issue:

**<h3><%= guides.user.try(:name) %></h3>**
**OR**
**<h3><%= guides.user.name if guides.user %></h3>**

I found similar issue here: [Link 1!](http://en.efreedom.net/Question/1-16153818/Development-Log-ActionView-Template-Error-Undefined-Method-Name-Nil-NilClass) [Link 2!](http://en.efreedom.net/Question/1-10840783/Test-Fail-ActionView-Template-Error-Undefined-Method-Name-Nil-NilClass)
I hope this helps. Let me know if it works.
