### ISSUE TITLE
Change availability data type

### ISSUE THREAD

**Issue by ardeshirj** [RadVenturepdx/Capn-Crunch#34]
Right now the data type for availability is a array of boolean, which is supported in postgres, but not sqlite.

We need to find a data type that works in both databases.

**Comment by lewisric** [comment]
Well.  Since boolean values are the issue we could just use 1's and 0's, because integers will work in both cases.  That would probably be the easiest and most time efficient/stable solution.

**Comment by ardeshirj** [comment]
The issue is the **array** of boolean. Seems like sqlite is not supporting array, so we need to find a common data type that works in both databases.

**Comment by lewisric** [comment]
Alright well our options in that case would either be to serialize the input or store it into something else (i.e. a JSON object).  We could probably just use a string honestly.

**Comment by ardeshirj** [comment]
Another option would be availability table that each column is a day in week, where each column is a date data type.

**Comment by lewisric** [comment]
That would also work

**Comment by beazley2** [comment]
Like I mentioned in the meeting, I think the way to go (barring getting postgres working on everyone's environment), is just to make seven different strings. I wanted to add the ability for Guides to give time ranges, and so if we use a time data type in ruby, you'd still need a minimum of two per day and it would be relatively inflexible. Strings allow for ranges, "11am - 3:30pm" or multiple ranges, "1p - 4p, 7p - 9p" and for non time preferences, "Unavailable" / "Availability varies by week" etc.

**Comment by beazley2** [comment]
If this is fine, I'll code it this afternoon.

**Comment by ardeshirj** [comment]
What is your thought to create availability table and join it to guide table.

This new table will have 7 columns that each represent a date-time. This will help us to fix the database issue, and let easier way to handle data and times together.

**Comment by beazley2** [comment]
Like I said, that's pretty inflexible. Only allows a single time per day which isn't really useful.

**Comment by ardeshirj** [comment]
Can you give an example of the string that you have in mind?

**Comment by beazley2** [comment]
There'd be seven of them:
sun_avail = "8am - 5pm"
mon_avail = "Unavailable"
tues_avail = "7am - 11am; 3pm - 7pm"
wed_avail = "Unavailable"
thurs_avail = "9am - 430pm"
fri_avail = "Varies by week. Contact for info"
sat_avail = "6am - 6pm"

**Comment by lewisric** [comment]
If we were to take the users ability to enter data and we limited it to selections we describe then we can avoid stupid user situation, it would also make it easier for formatting of calendars.

example format the string like:
A-20152801:0900-1500  (Available 1/28/2015 from 9am - 3pm)
Or
U-20152901 (Unavailable 01/29/2015)

 and parse strings as such

**Comment by beazley2** [comment]
Hmmm, does get a little trickier if we're going to incorporate it with the calendar. I was thinking this was more on their profile as general availability to give users an idea on when they could hire them. Guide could still refuse or take people outside their posted availability after user-guide contact.

**Comment by lewisric** [comment]
Regardless of what we go with we just need to stick to that paradigm so we don't have 50 different ways of formatting dates as we go along.

**Comment by lewisric** [comment]
Honestly if we even incorporate a calendar in the project is questionable being it's a stretch goal anyway so it shouldn't be a concern, and if we get to that point we're just going to pull a calendar API from google or some other site.

**Comment by beazley2** [comment]
@ardeshirj checkout availability-fixes branch, see if that'll work with sqlite when you get chance.

**Comment by ardeshirj** [comment]
Yes it does work with sqlite. Thanks for the changes.

**Comment by ardeshirj** [comment]
No need for PR since I merged it to my branch unless we need this changes before my PR.
