### ISSUE TITLE
Front-end change password

### ISSUE THREAD

**Issue by ardeshirj** [RadVenturepdx/Capn-Crunch#42]
We need a front-end page for change password page. Also we need to use the registration page for updating the user profile.

**Comment by CATcommander** [comment]
I think @sector46 took care of this already (correct me if I'm wrong). We can close this issue.

**Comment by sector46** [comment]
This is for the front-end page, what I did was back-end stuff. If the password change page isn't going to be changed in the front-end, then we can close it, but I think it's still open because we want to make it pretty.
