### ISSUE TITLE
Update Profile Country/State Dropdowns

### ISSUE THREAD

**Issue by lewisric** [RadVenturepdx/Capn-Crunch#72]
When you go to update your profile the dropdown updates to Canada always, which I assume will then save in the DB once the save occurs.

To reproduce:
Click account
Click Update Profile
Notice the dropdowns are not matching old location

**Comment by sector46** [comment]
I'm pretty sure I fixed this in the last PR I made, did you change your 'Country' attribute to something else, save it, then return to this screen?

**Comment by lewisric** [comment]
Yeah I tried that, heroku should auto deploy the latest master (I think). Let me check with @ardeshirj
