### ISSUE TITLE
Get Started and FAQ both link to FAQ

### ISSUE THREAD

**Issue by lewisric** [RadVenturepdx/Capn-Crunch#73]
Is this correct, i feel like it's not correct

**Comment by sector46** [comment]
What I'm seeing is two footers in static pages, I suspect that footer code was left in the static pages on top of the new footer file that was created. You may have clicked on the top footer, which will do some weird things

**Comment by lewisric** [comment]
we'll have to remove the static page footers if we're using a footer file correct?

**Comment by sector46** [comment]
I believe so, yes.
