### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by lewisric** [RadVenturepdx/Capn-Crunch#75]
![image](https://cloud.githubusercontent.com/assets/5631774/6380288/67ca08a8-bced-11e4-8de0-02f47655a002.png)

Does this occur because of lack of guide to populate the screen?

**Comment by lewisric** [comment]
@beazley2 @ardeshirj @sector46 
can one of you take a look at what it would take to not hardcode the values of the returned "top_guides" list.  It seems that in using {0, 1, 2} as our array indices will cause issues if no guide exists.  

OR maybe I'm an idiot and we resolved this already, but if I remember correctly from Thursday it was not resolved.

**Comment by beazley2** [comment]
It just requires some additional checks. If no one has implemented it yet I'll do it when I'm going through the merge conflicts on my branch.

**Comment by lewisric** [comment]
thank you sir
